Calidad_NeiserFinal/Models/Carta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calidad_NeiserFinal.Models
{
    public class Carta
    {
        public int Id { get; set; }
        public int Numero { get; set; }
        public string tipoCarta { get; set; }

        public int IdUsuario { get; set; }
    }
}

Calidad_NeiserFinal/Models/ErrorViewModel.cs
using System;

namespace Calidad_NeiserFinal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Calidad_NeiserFinal/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calidad_NeiserFinal.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Puntaje { get; set; }

    }
}

Calidad_NeiserFinal/Models/ValorCarta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Calidad_NeiserFinal.Models
{
    public class ValorCarta
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }

        public ValorCarta(int id, int cantidad)
        {
            Id = id;
            Cantidad = cantidad;
        }
    }
}

Calidad_NeiserFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Calidad_NeiserFinal.Models;

namespace Calidad_NeiserFinal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Calidad_NeiserFinal/Controllers/JuegoDePokerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Calidad_NeiserFinal.Models;
using Calidad_NeiserFinal.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;

namespace SimulacionPoker.Controllers
{
    public class JuegoDePokerController : Controller
    {
        private ICartaService _cartaService;
        private IUsuarioService _usuarioService;

        public JuegoDePokerController(ICartaService _cartaService,IUsuarioService _usuarioService)
        {
            this._cartaService = _cartaService;
            this._usuarioService = _usuarioService;
        }

        public IActionResult Index()
        {
            
         
            return View();
        }

        public IActionResult DetalleCartas(string Nombre1,string Nombre2,string Nombre3,string Nombre4,string Nombre5)
        {
            List<string> nueva = new List<string>();
            nueva.Add(Nombre1); nueva.Add(Nombre2); nueva.Add(Nombre3); nueva.Add(Nombre4); nueva.Add(Nombre5);
            var jugadores = Jugadores(nueva);
            
            
            var baraja = AsignarCartasJugadores();
            var jugador1 = baraja.Where(o => o.IdUsuario == 1).ToList();
            var jugador2 = baraja.Where(o => o.IdUsuario == 2).ToList();
            var jugador3 = baraja.Where(o => o.IdUsuario == 3).ToList();
            var jugador4 = baraja.Where(o => o.IdUsuario == 4).ToList();
            var jugador5 = baraja.Where(o => o.IdUsuario == 5).ToList();

            ViewBag.Jugador1 = jugador1;
            ViewBag.Jugador2 = jugador2;
            ViewBag.Jugador3 = jugador3;
            ViewBag.Jugador4 = jugador4;
            ViewBag.Jugador5 = jugador5;
         
            jugadores[0].Puntaje = puntaje(jugador1);
            jugadores[1].Puntaje = puntaje(jugador2);
            jugadores[2].Puntaje = puntaje(jugador3);
            jugadores[3].Puntaje = puntaje(jugador4);
            jugadores[4].Puntaje = puntaje(jugador5);
            Console.WriteLine("Jugador ganador");
            int contador = 0;
            var ValorMaximoPuntaje = jugadores.Max(o => o.Puntaje);
            var JugadoresGanadores = jugadores.Where(o => o.Puntaje == ValorMaximoPuntaje).ToList();
            @ViewBag.JugadoresGanadores = JugadoresGanadores;
            if (JugadoresGanadores.Count>1)
            {
                ViewBag.Mensaje = "Dos Ganadores";
            }
            else
            {
                ViewBag.Mensaje = "Ganador: ";
            }
 
            @ViewBag.Jugadores = jugadores;
            return View();
        }

        public List<Carta> AsignarBaraja()
        {
            var baraja = _cartaService.CrearBaraja();
            return baraja;
        }

        public List<string> TipoCarta()
        {
            var tipoDeCarta = _cartaService.TipoCarta();
            return tipoDeCarta;
        }

        public List<Carta> AsignarCartasJugadores()
        {
            var baraja = _cartaService.AsignarBarajaJugador();
            return baraja;
        }

        public List<User> Jugadores(List<string> nombres)
        {

            var jugadores = _usuarioService.Jugadores(nombres);
            return jugadores;
        }

        public int puntaje(List<Carta> mano)
        {
            var puntaje = _cartaService.Puntaje(mano);
            return puntaje;
           
        }
    }
}

Calidad_NeiserFinal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Calidad_NeiserFinal/Views/JuegoDePoker/DetalleCartas.cshtml
<div class="row">
    <div class="col-sm-2">
        Jugador: <strong>@ViewBag.Jugadores[0].Nombre</strong>
        <table class="table table-dark">
            <thead>
            <tr>

                <th>Numero</th>
                <th>Tipo</th>
          
            </tr>
            </thead>
            @foreach (var item in @ViewBag.Jugador1)
            {
                <tr>

                    <td>@item.Numero</td>
                    <td>@item.tipoCarta</td>
                    
                </tr>
            }

        </table>
        <h4>Puntaje: @ViewBag.Jugadores[0].Puntaje</h4>
    </div>
    <div class="col-sm-2">
        Jugador:<strong>@ViewBag.Jugadores[1].Nombre</strong>
        <table class="table table-dark">
            <thead>
                <tr>

                    <th>Numero</th>
                    <th>Tipo</th>

                </tr>
            </thead>
            @foreach (var item in @ViewBag.Jugador2)
            {
    <tr>

        <td>@item.Numero</td>
        <td>@item.tipoCarta</td>

    </tr>
   }

        </table>
        <h4>Puntaje: @ViewBag.Jugadores[1].Puntaje</h4>
    </div>
    <div class="col-sm-2">
        Jugador: <strong> @ViewBag.Jugadores[2].Nombre</strong>    
        <table class=" table table-dark">
            <thead>
                <tr>

                    <th>Numero</th>
                    <th>Tipo</th>

                </tr>
            </thead>
            @foreach (var item in @ViewBag.Jugador3)
            {
    <tr>

        <td>@item.Numero</td>
        <td>@item.tipoCarta</td>

    </tr>            }

        </table>
        <h4>Puntaje: @ViewBag.Jugadores[2].Puntaje</h4>
    </div>
    <div class="col-sm-2">
        Jugador: <strong> @ViewBag.Jugadores[3].Nombre</strong>
        <table class="table table-dark">
            <thead>
                <tr>

                    <th>Numero</th>
                    <th>Tipo</th>

                </tr>
            </thead>
            @foreach (var item in @ViewBag.Jugador4)
            {
    <tr>

        <td>@item.Numero</td>
        <td>@item.tipoCarta</td>

    </tr>            }

        </table>
        <h4>Puntaje: @ViewBag.Jugadores[3].Puntaje</h4>
    </div>
    <div class="col-sm-2">
        Jugador: <strong> @ViewBag.Jugadores[2].Nombre</strong>
        <table class="table table-dark">
            <thead>
                <tr>

                    <th>Numero</th>
                    <th>Tipo</th>

                </tr>
            </thead>
            @foreach (var item in @ViewBag.Jugador5)
            {
    <tr>

        <td>@item.Numero</td>
        <td>@item.tipoCarta</td>

    </tr>            }

        </table>
        <h4>Puntaje: @ViewBag.Jugadores[4].Puntaje</h4>
    </div>
</div>
<strong>@ViewBag.Mensaje</strong>
@foreach (var item in @ViewBag.JugadoresGanadores)
{
<h2>
    @item.Nombre @item.Puntaje Pts


</h2>
    
}

Calidad_NeiserFinal/Views/JuegoDePoker/Index.cshtml
<head>
	
</head>
<body>
<div class="jugadores">
	<form method="post"  action="/JuegoDePoker/DetalleCartas">
		<input type="text" name="Nombre1" placeholder="jugador 1" required="required" />
		<input type="text" name="Nombre2" placeholder="jugador 2" required="required" />
		<input type="text" name="Nombre3" placeholder="jugador 3" required="required" />
		<input type="text" name="Nombre4" placeholder="jugador 4" required="required" />
		<input type="text" name="Nombre5" placeholder="jugador 5" required="required" />
		
		<button type="submit" class="btn btn-primary ">Jugar</button>
	</form>
</div>
</body>

Calidad_NeiserFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calidad_NeiserFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Calidad_NeiserFinal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JuegoDePoker" asp-action="Index">Jugar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Calidad_NeiserFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>